sudo: true

# addons:
  # apt:
    # packages:
    # - apache2
    # - elinks


before_install:
# - sudo apt install aptitude # already installed
- sudo aptitude update -Z
# - sudo aptitude safe-upgrade -Z --assume-yes
# - sudo aptitude install elinks --assume-yes
- sudo aptitude install apache2 -Z --assume-yes
- sudo aptitude install links2 -Z --assume-yes


script:
- service apache2 status
- links2 -g -dump http://localhost:80


after_script:
- ls -l --color /var/www
- ls -dl --color /var/www/html
- ls --color /var/www/html
- zcat /usr/share/doc/apache2/README.Debian.gz
